algoritmo "Natação"

var
idade: inteiro
inicio
ESCREVAL("Digite a idade do nadador: ")
LEIA (idade)
ESCOLHA idade
caso 5, 6, 7
ESCREVAL("Infantil A")

caso 8, 9, 10
ESCREVAL ("Infantil B")

caso 11, 12, 13
ESCREVAL ("Juvenil A")

caso 14, 15, 16, 17
ESCREVAL ("Juvenil B")

caso 18, 19, 20, 21, 22, 23, 24, 25
ESCREVAL ("Sênior")

OUTROCASO
ESCREVAL("Idade fora da faixa etária")
FIMESCOLHA


fimalgoritmo

