algoritmo "comparar_valores"

var
valor1, valor2: inteiro

inicio
escreval("Digite o primeiro valor: ")
leia (valor1)

escreval("Digite o segundo valor: ")
leia(valor2)

se (valor1 > valor2) entao
escreval(valor1, " é maior que " ,valor2)
fimse

se (valor1 < valor2) entao
escreval (valor2, " é maior que " ,valor1)
fimse

se (valor1 = valor2) entao
escreval ("Os valores são iguais o mongol")
fimse


fimalgoritmo
