algoritmo "Exercicio2"

var
genero: caractere

inicio
Escreval("Que genero você é? Apenas F=Feminno e M=masculino")
leia(genero)
            se genero = "F" entao
            escreval("Você é mulher!")
             senao
            se genero = "M" entao
            escreval("Você é homem!")
            senao
            escreval("Informe um genero válido")
fimse
fimse


fimalgoritmo
