algoritmo "Média"

var
ValorA, ValorB, ValorC, ValorD, ValorE, Media: real

inicio

escreval("Digite o Valor de A: ")
leia(ValorA)
escreval("Digite o Valor de B: ")
leia(ValorB)
escreval("Digite o Valor de C: ")
leia(ValorC)
escreval("Digite o Valor de D: ")
leia(ValorD)
escreval("Digite o Valor de E: ")
leia(ValorE)

//Processando Operações

Media <- ((ValorA+ValorB+ValorC+ValorDValorE)/5)

fimalgoritmo
